#!/usr/bin/perl
use strict;
use Term::ANSIColor;
use feature 'unicode_strings';

chomp(my $current_branch = `git rev-parse --abbrev-ref HEAD`);
my $test_command = "gulp specs";

if ($current_branch eq "master") {
    print color('bold yellow');
    print "\n(ಠ_ಠ) (ಠ_ಠ) (ಠ_ಠ) (ಠ_ಠ) (ಠ_ಠ) (ಠ_ಠ) \n\n";
    print color('bold red');
    print "You're on the master branch, bro. Pump the brakes and lets make you a new branch  \n\n";
    print color('magenta');
    print "Enter the name of your new branch or bail by blasting ctrl-c : ";
    chomp(my $new_branch = <STDIN>);
    &make_new_branch($new_branch);
}

print color('bold green');
print "\nHey, bro. Lets make a PR. \n\nFirst lets run those specs and push to this nice new branch you got here\n\n\n";
print color('bold blue');
print "your current branch is: ";
print color('bold magenta');
print "$current_branch\n\n";
&run_specs_and_push();

sub run_specs_and_push {
    print color('bold red');

    system($test_command) == 0
        or die "\n\n (╯°□°）╯︵ ┻━┻ \n\nLooks like your tests are hosed, bro.
        \nYou should check that out before you push this up and make one of those sweet pull requests.\n";

    system("git push -u origin $current_branch") == 0
        or die "\n ¯\_(ツ)_/¯ Well something not very chill is going on here. Your push blew up ¯\_(ツ)_/¯\n";

    print color('bold blue');
    print "\n\n Just pushed, go open your PR, bro. You're the best developer ever.";
    print color('bold yellow');
    print "   ◕‿↼ \n\n\n";
}

sub make_new_branch {
    print color("bold red");
    system("git checkout -b $_[0]") == 0
        or die "\n ¯\_(ツ)_/¯ Well something not very chill is going on here.
                    Your new branch checkout blew up ¯\_(ツ)_/¯\n";
}